### ISSUE TITLE
Account alert button overlapping other buttons

### ISSUE THREAD

**Issue by LoVega1337** [ungstein/OG-Steam#1]
Hey there, I've noticed that the "Account alert" button overlaps over the Store, library, etc buttons as seen in the screenshot below.
![image](https://user-images.githubusercontent.com/47011400/125787217-719b3308-0a2f-48d9-8854-e8b35cebdca9.png)

It should be next to the notifications like here:
![image](https://user-images.githubusercontent.com/47011400/125787833-e0878fe4-e785-4610-8d5e-b6de2e21f7a4.png)

**Comment by ungstein** [comment]
Thanks for pointing this out. I will fix it in the next release.

**Comment by ungstein** [comment]
I don't think I will be able to replicate this issue because I do not have any account alerts. Would you be able to start Steam in dev mode (steam.exe -dev) and use the VGUI debugger to tell me the name of the control? The debugger tends to only launch when you mouse over a button and press F6. Once it's running, just click on the button and its information will show up in the debugger. If you could provide me with a screenshot of the debugger, this would help greatly.

**Comment by LoVega1337** [comment]
Here you go 🙂

![image](https://user-images.githubusercontent.com/47011400/126034055-965698cc-9270-49e8-a0a6-f2f38e0a7af5.png)
![image](https://user-images.githubusercontent.com/47011400/126034062-f42c9bcb-15de-4863-b536-37de79f28833.png)
![image](https://user-images.githubusercontent.com/47011400/126034092-1f1ef086-ac82-4c69-8c8a-d7c570e576a7.png)

**Comment by ungstein** [comment]
This is perfect, thanks!

**Comment by ungstein** [comment]
Ok, try using the latest source; it should be fixed now. If it is, I'll make a new release.

**Comment by LoVega1337** [comment]
Yup, it's at the correct place now.

![Screenshot 2021-07-17 171832](https://user-images.githubusercontent.com/47011400/126041512-bf821716-4f91-474c-83d5-3ff54dc6d333.png)

Although, the button ends directly where the text ends, not a big issue, but something I noticed. Maybe this is an inset issue?
![image](https://user-images.githubusercontent.com/47011400/126041662-55c7b1e1-4815-4429-a726-af4cafaf8f73.png)

**Comment by ungstein** [comment]
Hmm. Definitely looks like an inset or padding issue. I'll take a look.

**Comment by ungstein** [comment]
Okay so I've reduced the padding on both sides and removed some obsolete image references, but I couldn't find anything that defines the button width, so it may be fixed.

I take it you have some experience with VGUI, so here is the section I'm looking at:

steamrootdialog.layout:301

```
		support_alert
		{
			font-family=basefont
			font-size=14
			font-weight=1000
			font-style=none
			textcolor=white
			padding-left=8
			padding-right=8
			padding-top=6
			inset="-8 -3 8 0"
			render {}
			render_bg
			{
				0="fill( x0, y0, x1, y1+1, parental_lock_inactive1 )"
			}
		}
		
		support_alert:hover
		{
			font-family=basefont
			font-size=14
			font-weight=1000
			font-style=none
			textcolor=white
			padding-left=8
			padding-right=8
			padding-top=6
			inset="-8 -3 8 0"
			render {}
			render_bg
			{
				0="fill( x0, y0, x1, y1, parental_lock_inactive3 )"
			}
		}
```

Hopefully it looks okay now, but if not, feel free to play around. I am open to pull requests.

**Comment by LoVega1337** [comment]
I tried your solution and also played with the inset a bit, but it's still the same unfortunately.
Since the initial issue has been fixed though I'll close this issue and play around if I can fix the text myself and open a pull request.
